### ISSUE TITLE
Onde eu encontro a documentação 

### ISSUE THREAD

**Issue by vicenthy** [fabricadecodigo/DeliveryAppRestauranteIonic#1]
onde fica a documentação com os dados que tenho que exibir na tela?

**Comment by feliperfranco** [comment]
@vicenthy o backend ainda não está pronto.
Estou apenas iniciando a prototipação das telas para saber o que eu preciso fazer no backend.
Vai acompanhando as aulas

**Comment by vicenthy** [comment]
blz
